apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: back-end
          image: 589347534073.dkr.ecr.ap-southeast-2.amazonaws.com/eks-api:latest
          ports:
            - containerPort: 80